[build]
  functions = "src/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/graphql-api"
  status = 200
  force = true
