name: Release to Netlify

on:
  push:
    tags:
      - '*'

jobs:
  release-to-netlify:
    uses: 'chrisw-b/ci-cd/.gitea/workflows/deploy-to-netlify.yml@v4.1'
    secrets: inherit
    with:
      PR_NUMBER: ${{ gitea.event.number }}
      NETLIFY_CONTEXT: 'production'
