name: Lint Project

on:
  pull_request:
    branches: [main]

jobs:
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: npm i --no-savec --no-fund --no-audit --no-progress

      - run: npm run prettier:check

  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: npm i --no-savec --no-fund --no-audit --no-progress

      - run: npm run lint:js

  check-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - run: npm i --no-savec --no-fund --no-audit --no-progress

      - run: npm run typescript
